'use client';
import Head from 'next/head';
import styles from '@/styles/Home.module.scss';
import NavBar from '@/components/nav-bar';
import HomePage from '@/components/home';
import React,{useEffect} from 'react';

export default function Home() {

  useEffect(()=>{
    (async () => {
      const LocomotiveScroll = (await import('locomotive-scroll')).default
      const locomotiveScroll = new LocomotiveScroll();
    })();
  },[])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`} id="main">
        <NavBar/>
        <HomePage/>
      </main>
    </>
  )
}
